spring:
  application:
    name: InsultBoard
  datasource:
    url: jdbc:postgresql://localhost:5432/insultdb
    username: postgres
    password: bump567*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  address: 0.0.0.0
  port: 8080
